### ISSUE TITLE
Lỗi - In phiếu thu đã đồng bộ hóa đơn điện tử (BV Phong Điền)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalfees#149]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92008`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phong Điền**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phongdien_hddt_08012023_1`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_phongdien_hddt_08012023_1`](https://gofile.me/78TQg/DrJbscNSj)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000361` - _**MaKB**_: `2401002433` - _**NgayKCB**_: `08/01/2024` - _**MaPhong**_: `04` - _**MaDV**_: `10` -_**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Soctnoibo**_: `V1.00258/01`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Fees in phiếu thu đã đồng bộ hóa đơn điện tử báo lỗi.

Error [0]Message: Lỗi xảy ra tại [Name:Void HosFees.FormsV2.FrmCPhiBenhNhan.PrintPhieuthu(),Assembly:HosFees.dll,Version: Version=3.23.1221.7].
Error [0]HResult: -2146233088
Error [0]Source: HosFees
Error [0]StackTrace:    at HosFees.FormsV2.FrmCPhiBenhNhan.PrintPhieuthu()
   at HosFees.FormsV2.FrmCPhiBenhNhan.btnClick(Object sender, EventArgs e)
Error [0]TargetSite: Void PrintPhieuthu()

Error [1]=== INNER EXCEPTION ===
Error [1]Message: Lỗi xảy ra tại [Name:OTH.Entity.current.thuchi OTH.Adapter.HosFees.ApiHddt.FindThuChi(System.String, System.String, System.String),Assembly:OTH.Adapter.dll,Version: Version=1.23.1231.1].
Tham số truyền vào [{"[Name]":"mabn","[Type]":"System.String","[Value]":"2024000361"},{"[Name]":"makb","[Type]":"System.String","[Value]":"2401002433"},{"[Name]":"soct","[Type]":"System.String","[Value]":"V1.00258/01"}]
Error [1]HResult: -2146233088
Error [1]Source: OTH.Adapter
Error [1]StackTrace:    at OTH.Adapter.HosFees.ApiHddt.FindThuChi(String mabn, String makb, String soct)
   at HosFees.FormsV2.FrmCPhiBenhNhan.PrintPhieuthu()
Error [1]TargetSite: OTH.Entity.current.thuchi FindThuChi(System.String, System.String, System.String)



Error [2]=== EXCEPTION POSTGRESQL===
[BaseMessage]:column "hddt_dongia" does not exist

[ErrorSql]:SELECT COALESCE(soct,'') AS soct ,COALESCE(loai,'') AS loai ,COALESCE(khct,'') AS khct ,ngayct,COALESCE(mabn,'') AS mabn ,COALESCE(makb,'') AS makb ,COALESCE(madt,'') AS madt ,noitru,COALESCE(madv,'') AS madv ,COALESCE(maphong,'') AS maphong ,COALESCE(lydo,'') AS lydo ,COALESCE(nguoigiao,'') AS nguoigiao ,COALESCE(nguoinhan,'') AS nguoinhan ,tongtien,ptthu,thucthu,dain,COALESCE(taikhoan,'') AS taikhoan ,COALESCE(tenmay,'') AS tenmay ,xoa,ngayxoa,COALESCE(thangkt,'') AS thangkt ,COALESCE(namkt,'') AS namkt ,COALESCE(quyen,'') AS quyen ,COALESCE(sobl,'') AS sobl ,thucthuct,COALESCE(psmato,'') AS psmato ,COALESCE(psdabaocao,'') AS psdabaocao ,tygia,loaibldv,miengiam,thatthu,COALESCE(soctbltong,'') AS soctbltong ,COALESCE(diachi,'') AS diachi ,COALESCE(masothue,'') AS masothue ,COALESCE(tendonvibn,'') AS tendonvibn ,COALESCE(phienban,'') AS phienban ,tamung,tuoi,dvttuoi,psptthu,psvanchuyen,chuyenpt,thucthubh,thucthutp,thuesuat,COALESCE(chuyenptluu,'') AS chuyenptluu ,COALESCE(tachhd,'') AS tachhd ,ptthu_bh2,thucthubh_bh2,psvanchuyen_bh2,solanin,mienchitra_bh2,mienchitra,COALESCE(theodoi,'') AS theodoi ,COALESCE(nammp,'') AS nammp ,COALESCE(thangmp,'') AS thangmp ,ngaymp,nhathuoc,COALESCE(lydo_thuong,'') AS lydo_thuong ,COALESCE(lydo_dichvu,'') AS lydo_dichvu ,tachhd_ps,thucthu_thuong,thucthu_dichvu,COALESCE(hinhthucthanhtoan,'') AS hinhthucthanhtoan ,mgdongchitracls,thucthu_dongchitracls,synchddt,COALESCE(resulthddt,'') AS resulthddt ,COALESCE(jsondatahddt,'') AS jsondatahddt ,COALESCE(filebytes,'') AS filebytes ,ngaysynchddt,thatthuchenhlech,COALESCE(khct_hddt,'') AS khct_hddt ,COALESCE(sobl_hddt,'') AS sobl_hddt ,COALESCE(quyen_hddt,'') AS quyen_hddt ,COALESCE(hddtprefixfkey,'') AS hddtprefixfkey ,COALESCE(taikhoanthue,'') AS taikhoanthue ,thucthu_dichvunt,COALESCE(lydo_dichvunt,'') AS lydo_dichvunt ,nguonkhac,COALESCE(filebytespdf,'') AS filebytespdf ,thuesuathddt,COALESCE(matracuu_hddt,'') AS matracuu_hddt ,COALESCE(filebytespdfrepresentation,'') AS filebytespdfrepresentation ,COALESCE(pay_payid,'') AS pay_payid ,thucthu_pay,loaikh,hddt_dongia,hddt_soluong,COALESCE(hddt_dvt,'') AS hddt_dvt ,COALESCE(pay_type,'') AS pay_type  FROM current.thuchi WHERE  COALESCE(mabn,'')  =  '2024000361'   AND  COALESCE(makb,'')  =  '2401002433'   AND  COALESCE(soct,'')  =  'V1.00258/01'   AND  xoa  =  0  LIMIT 1; 

[Routine]:errorMissingColumn

[Detail]:

Error [2]=== INNER EXCEPTION ===
Error [2]Message: ERROR: 42703: column "hddt_dongia" does not exist
Error [2]HResult: -2147467259
Error [2]Source: OTH
Error [2]StackTrace:    at OTH.ClsPostgres.CmdPgSQL.GetDataTable(String sSQL)
   at OTH.ClsPostgres.CmdPgSQL.getFirstRow(String sSQL)
   at OTH.Adapter.HosFees.ApiHddt.FindThuChi(String mabn, String makb, String soct)
Error [2]TargetSite: System.Data.DataTable GetDataTable(System.String)

```
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/45e4fbb1-c9c6-4135-b22e-02a1c9767ddf)

**Comment by ongtrieuhau-dh** [comment]
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/155862740/abbbcc05-8d9d-408e-a5d4-2beae4c09561)
Cập nhật cấu trúc nhé

**Comment by ongtrieuhau-dh** [comment]
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/155862740/e6d24073-71bf-4f2a-b3b5-437a15eafb84)

**Comment by le-an-87** [comment]
đã in được hóa đơn!
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/bfb7d962-6d50-40fd-b43b-78c5b1752d94)
